[participants.0]
output_column_names = ["date",  "sales", "total", "rank", "net result", "total", "rank", "EBITDA", "total", "rank", "cash flow", "total", "rank", "cash position", "total", "rank"]
[participants.1]
output_column_names = ["date",  "sales", "total", "rank", "net result", "total", "rank", "EBITDA", "total", "rank", "cash flow", "total", "rank", "cash position", "total", "rank"]
[participants.2]
output_column_names = ["date",  "sales", "total", "rank", "net result", "total", "rank", "EBITDA", "total", "rank", "cash flow", "total", "rank", "cash position", "total", "rank"]